/**
 * Blog post renderer. The page embeds its content as window.BLOG (generated by
 * build_blogs.py from the blog's source file); this walks the sections and renders
 * prose + justified photo grids (gallery.js, sequential order preserved).
 *
 * ui:"v2" (per-blog opt-in in config/blogs.json) layers on:
 *   - a thin reading-progress bar under the topnav
 *   - a sticky "day chip" rail built from the day headings, with scroll-spy
 *   - day headings restyled as structured strips (DAY N eyebrow · route · km chip)
 *   - a back-to-top button
 */
(function () {
  const data = window.BLOG || { sections: [] };
  const root = document.getElementById('blog');
  if (!root) return;
  const v2 = data.ui === 'v2';

  const DAY_RE = /^Day\s*(\d+(?:\s*&\s*\d+)?)\s*[:\-–]*\s*(.*)$/i;
  const KM_RE = /\s*(\d[\d,]*)\s*km\b/i;

  function plain(html) {
    const d = document.createElement('div');
    d.innerHTML = html;
    return d.textContent || '';
  }

  const dayAnchors = [];   // {id, label, el}

  data.sections.forEach(sec => {
    if (sec.type === 'heading') {
      const text = plain(sec.html);
      const m = v2 && text.match(DAY_RE);
      if (m) {
        const id = 'day-' + m[1].replace(/\s*&\s*/, '-');
        const wrap = document.createElement('div');
        wrap.className = 'day-strip';
        wrap.id = id;
        // strip a redundant repeated "Day N:" prefix (source typo) from the title
        let rest = (m[2] || '').replace(/^Day\s*\d+(?:\s*&\s*\d+)?\s*[:\-–]*\s*/i, '');
        let km = '';
        const k = rest.match(KM_RE);
        if (k) {
          km = k[1] + ' km';
          rest = rest.replace(KM_RE, '').trim();
        }
        wrap.innerHTML =
          '<div class="day-eyebrow">Day ' + m[1] + '</div>' +
          '<h2 class="day-title">' + (rest || '&nbsp;') + '</h2>' +
          (km ? '<div class="day-km">' + km + '</div>' : '');
        root.appendChild(wrap);
        dayAnchors.push({ id, label: 'Day ' + m[1], el: wrap });
        return;
      }
      const h = document.createElement(sec.level >= 3 ? 'h3' : 'h2');
      h.innerHTML = sec.html;
      root.appendChild(h);
    } else if (sec.type === 'text') {
      sec.paragraphs.forEach(p => {
        const el = document.createElement('p');
        el.innerHTML = p;
        root.appendChild(el);
      });
    } else if (sec.type === 'photos') {
      const g = document.createElement('div');
      g.className = 'blog-grid';
      root.appendChild(g);
      window.Gallery.renderGrid(g, sec.photos, { sequential: true });
    }
  });

  if (!v2) return;

  // ── reading progress bar ──
  const bar = document.createElement('div');
  bar.className = 'read-progress';
  document.body.appendChild(bar);
  function onScroll() {
    const h = document.documentElement;
    const max = h.scrollHeight - h.clientHeight;
    bar.style.width = (max > 0 ? (h.scrollTop / max) * 100 : 0) + '%';
  }
  document.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  // ── sticky day rail with scroll-spy ──
  if (dayAnchors.length > 1) {
    const rail = document.createElement('nav');
    rail.className = 'day-rail';
    const inner = document.createElement('div');
    inner.className = 'day-rail-inner';
    rail.appendChild(inner);
    dayAnchors.forEach(a => {
      const chip = document.createElement('a');
      chip.className = 'day-chip';
      chip.textContent = a.label;
      chip.href = '#' + a.id;
      chip.addEventListener('click', e => {
        e.preventDefault();
        a.el.scrollIntoView({ behavior: 'smooth', block: 'start' });
        history.replaceState(null, '', '#' + a.id);
      });
      a.chip = chip;
      inner.appendChild(chip);
    });
    document.querySelector('.blog-wrap').before(rail);

    const spy = new IntersectionObserver(() => {
      // active = last day heading above the viewport's upper third
      const cut = window.innerHeight * 0.35;
      let active = dayAnchors[0];
      dayAnchors.forEach(a => {
        if (a.el.getBoundingClientRect().top <= cut) active = a;
      });
      dayAnchors.forEach(a => a.chip.classList.toggle('active', a === active));
      if (active.chip.scrollIntoView) {
        inner.scrollTo({ left: active.chip.offsetLeft - 24, behavior: 'smooth' });
      }
    }, { rootMargin: '0px', threshold: [0, 1] });
    dayAnchors.forEach(a => spy.observe(a.el));
  }

  // ── back to top ──
  const top = document.createElement('button');
  top.className = 'to-top';
  top.title = 'Back to top';
  top.innerHTML = '↑';
  top.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
  document.body.appendChild(top);
  document.addEventListener('scroll', () => {
    top.classList.toggle('show', document.documentElement.scrollTop > 1200);
  }, { passive: true });
})();
