/**
 * Owner-only Instagram post drafts ("Posts").
 *
 * Included on every photo page but completely inert unless the posts_auth
 * cookie is present (set by /auth-posts, a separate owner-only password):
 * no DOM, no network, no CSS. The server re-checks the cookie on every
 * /api/posts call, so a forged cookie only ever produces 404s.
 *
 * Surfaces when unlocked:
 *  - Sitewide "Posts mode" pill (bottom-left) linking to /posts, with an ✕
 *    that exits posts mode by clearing the cookie.
 *  - "+ Post" button in every PhotoSwipe top bar (hooked via attachLightbox).
 *  - Select mode on photo grids (hooked via onGridRender from gallery.js).
 *  - The /posts manager page (initPostsPage, called by posts.html).
 *
 * All state lives server-side in one versioned JSON doc; every mutation is a
 * re-appliable function so a 409 (edited on another device) can merge cleanly.
 */
window.Posts = (function () {
    function unlocked() {
        return document.cookie.split(';').some(c => {
            const t = c.trim();
            return t.startsWith('posts_auth=') && t.length > 'posts_auth='.length;
        });
    }

    // ---------- Locked: no-op stubs + the /posts password prompt ----------

    function renderPasswordForm(root) {
        root.innerHTML = `
            <div class="posts-login">
                <h1>Posts</h1>
                <input type="password" id="posts-pw" placeholder="Password" autocomplete="current-password">
                <p class="posts-login-error" id="posts-pw-error"></p>
                <button type="button" id="posts-pw-submit">Enter</button>
            </div>`;
        const input = root.querySelector('#posts-pw');
        const error = root.querySelector('#posts-pw-error');
        async function submit() {
            const fd = new FormData();
            fd.append('password', input.value);
            try {
                const r = await fetch('/auth-posts', { method: 'POST', body: fd });
                if (r.ok) location.reload();
                else error.textContent = 'Incorrect password';
            } catch (err) {
                error.textContent = 'Error: ' + err.message;
            }
        }
        input.addEventListener('keydown', e => { if (e.key === 'Enter') submit(); });
        root.querySelector('#posts-pw-submit').addEventListener('click', submit);
        input.focus();
    }

    if (!unlocked()) {
        return {
            enabled: false,
            attachLightbox() {},
            onGridRender() {},
            initPostsPage() {
                const root = document.getElementById('posts-app');
                if (root) renderPasswordForm(root);
            }
        };
    }

    // ---------- Unlocked ----------

    const cssLink = document.createElement('link');
    cssLink.rel = 'stylesheet';
    cssLink.href = '/css/posts.css';
    document.head.appendChild(cssLink);

    // Sitewide "Posts mode" pill: shows on every page while the posts_auth
    // cookie is present, links to the /posts manager, and its ✕ exits posts
    // mode by clearing the cookie (it is not HttpOnly, so JS can).
    function exitPostsMode() {
        if (!confirm('Exit posts mode? You will need the posts password to get back in.')) return;
        document.cookie = 'posts_auth=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;'
            + (location.protocol === 'https:' ? ' Secure;' : '');
        location.reload();
    }

    (function addModePill() {
        const pill = document.createElement('div');
        pill.id = 'posts-pill';
        const link = document.createElement('a');
        link.href = '/posts';
        link.textContent = 'Posts mode';
        link.title = 'Open the posts manager';
        const exit = document.createElement('button');
        exit.type = 'button';
        exit.title = 'Exit posts mode';
        exit.textContent = '✕';
        exit.addEventListener('click', exitPostsMode);
        pill.append(link, exit);
        document.body.appendChild(pill);
    })();

    // "Posts" entry in the nav "More" dropdown while posts mode is on. The
    // script loads at the end of body, so the nav is already in the DOM.
    document.querySelectorAll('.nav-more-menu').forEach(menu => {
        if (menu.querySelector('a[href="/posts"]')) return;
        const a = document.createElement('a');
        a.href = '/posts';
        a.textContent = 'Posts';
        menu.appendChild(a);
    });

    let doc = null;           // manual drafts { version, posts }; null on failure
    let autoDoc = null;       // auto-curated suggestions doc (/posts page only)
    let saveChain = Promise.resolve();

    const ready = fetch('/api/posts', { cache: 'no-store' })
        .then(r => (r.ok ? r.json() : null))
        .then(d => { doc = d; return !!d; })
        .catch(() => false);

    // The auto set (machine-generated by tools/auto_curate_posts.py) is a
    // second independent doc; only the /posts manager needs it, so it loads
    // lazily there.
    let autoReadyP = null;
    function autoReady() {
        if (!autoReadyP) {
            autoReadyP = fetch('/api/posts?set=auto', { cache: 'no-store' })
                .then(r => (r.ok ? r.json() : null))
                .then(d => { autoDoc = d; return !!d; })
                .catch(() => false);
        }
        return autoReadyP;
    }

    // Every mutation is a function of (posts) that can be re-applied to a fresh
    // server copy after a 409, so concurrent edits from another device merge
    // instead of clobbering. Mutations are serialized through saveChain.
    function mutateSet(set, fn) {
        const get = () => (set === 'auto' ? autoDoc : doc);
        const run = async () => {
            if (!get()) throw new Error('posts unavailable');
            fn(get().posts);
            const url = '/api/posts' + (set === 'auto' ? '?set=auto' : '');
            const put = () => fetch(url, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ baseVersion: get().version, posts: get().posts })
            });
            let r = await put();
            if (r.status === 409) {
                const fresh = await r.json();
                if (set === 'auto') autoDoc = fresh; else doc = fresh;
                fn(get().posts);
                r = await put();
            }
            if (!r.ok) throw new Error('save failed (' + r.status + ')');
            get().version = (await r.json()).version;
        };
        saveChain = saveChain
            .then(run)
            .then(() => true, err => { toast('Save failed: ' + err.message); return false; });
        return saveChain;
    }
    function mutate(fn) { return mutateSet('main', fn); }

    const MAX_PHOTOS = 20;   // Instagram carousel limit

    const keyOf = ref => `${ref.trip}::${ref.id || ref.file}`;
    const plural = n => `${n} photo${n === 1 ? '' : 's'}`;
    const newId = () => 'p' + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);

    function defaultName(posts) {
        let n = posts.length + 1;
        while (posts.some(p => p.name === `Post ${n}`)) n++;
        return `Post ${n}`;
    }

    // Strip to the fields the API accepts (grid/lightbox refs can carry extras).
    function cleanRef(ref) {
        const out = { trip: ref.trip, id: ref.id };
        if (typeof ref.ar === 'number') out.ar = ref.ar;
        return out;
    }

    // Phone items are {trip, id} photos or {trip, file} videos from the
    // local-only phone library.
    function cleanPhoneRef(ref) {
        const out = { trip: ref.trip };
        if (ref.id) out.id = ref.id; else out.file = ref.file;
        if (typeof ref.ar === 'number') out.ar = ref.ar;
        return out;
    }

    function addRefsToPost(post, refs) {
        const have = new Set(post.photos.map(keyOf));
        const havePhone = new Set((post.phone || []).map(keyOf));
        let added = 0, dupes = 0, hitCap = false, phoneAdded = 0;
        refs.forEach(ref => {
            // Phone-library items live in their own bucket: behind-the-scenes
            // companions to the carousel, exempt from the 20-photo cap.
            if (ref.trip && ref.trip.startsWith('phone-')) {
                if (havePhone.has(keyOf(ref))) { dupes++; return; }
                if (!post.phone) post.phone = [];
                post.phone.push(cleanPhoneRef(ref));
                havePhone.add(keyOf(ref));
                added++; phoneAdded++;
                return;
            }
            if (have.has(keyOf(ref))) { dupes++; return; }
            if (post.photos.length >= MAX_PHOTOS) { hitCap = true; return; }
            post.photos.push(cleanRef(ref));
            have.add(keyOf(ref));
            added++;
        });
        return { added, dupes, hitCap, phoneAdded, count: post.photos.length };
    }

    // The "current post": the last post photos were added to (or picked in the
    // sheet). "+ Post" and "Add to post" go straight here without re-asking.
    const TARGET_KEY = 'posts_target_id';
    function targetPost() {
        if (!doc) return null;
        let id = null;
        try { id = localStorage.getItem(TARGET_KEY); } catch (e) { /* private mode */ }
        return (id && doc.posts.find(p => p.id === id)) || null;
    }
    function setTarget(id) {
        try { localStorage.setItem(TARGET_KEY, id); } catch (e) { /* private mode */ }
    }

    // ---------- Small UI primitives ----------

    let toastTimer;
    function toast(msg) {
        let el = document.getElementById('posts-toast');
        if (!el) {
            el = document.createElement('div');
            el.id = 'posts-toast';
            document.body.appendChild(el);
        }
        el.textContent = msg;
        el.classList.add('visible');
        clearTimeout(toastTimer);
        toastTimer = setTimeout(() => el.classList.remove('visible'), 2200);
    }

    /** Refs that already live in ANOTHER post (drafts, not auto suggestions):
     *  [{ref, post}] pairs, so the add flow can warn before double-posting. */
    function conflictsFor(refs, targetId) {
        const out = [];
        if (!doc) return out;
        refs.forEach(ref => {
            const k = keyOf(ref);
            doc.posts.forEach(p => {
                if (p.id === targetId) return;
                if (p.photos.some(ph => keyOf(ph) === k) ||
                    (p.phone || []).some(ph => keyOf(ph) === k)) {
                    out.push({ ref, post: p });
                }
            });
        });
        return out;
    }

    /** Add refs to a post (creating it if postId is new), remember it as the
     *  current post, and toast the outcome. Duplicates are skipped and named.
     *  Photos already used by a different post get an add-anyway/cancel
     *  confirm naming that post, so nothing is double-posted by accident. */
    function addToPost(postId, refs, onDone) {
        const conflicts = conflictsFor(refs, postId);
        if (conflicts.length) {
            const names = [...new Set(conflicts.map(c => c.post.name))];
            const nDup = new Set(conflicts.map(c => keyOf(c.ref))).size;
            const msg = refs.length === 1
                ? `This photo is already in "${names[0]}". Add anyway?`
                : `${nDup} of these photos are already in other posts (${names.join(', ')}). Add anyway?`;
            if (!confirm(msg)) return;
        }
        const result = {};
        mutate(posts => {
            let post = posts.find(p => p.id === postId);
            if (!post) {
                post = { id: postId, name: defaultName(posts), created: new Date().toISOString(), photos: [] };
                posts.push(post);
            }
            result.name = post.name;
            Object.assign(result, addRefsToPost(post, refs));
        }).then(okSave => {
            if (!okSave) return;
            setTarget(postId);
            updateSelectUi();
            restampSelections();
            if (result.phoneAdded && result.added === result.phoneAdded) {
                toast(`Added ${result.phoneAdded > 1 ? result.phoneAdded + ' ' : ''}to ${result.name} (Phone section, no cap)`);
            } else if (result.hitCap && result.added) {
                toast(`Added ${result.added}, ${result.name} is now full (${MAX_PHOTOS}/${MAX_PHOTOS})`);
            } else if (result.hitCap) {
                toast(`${result.name} is full (${MAX_PHOTOS}/${MAX_PHOTOS})`);
                return;   // nothing was added, keep the selection
            } else if (!result.added) {
                toast(refs.length === 1
                    ? `Already in ${result.name} (${result.count}/${MAX_PHOTOS})`
                    : `All ${refs.length} already in ${result.name} (${result.count}/${MAX_PHOTOS})`);
                return;   // nothing was added, keep the selection
            } else if (result.dupes) {
                toast(`Added ${result.added} to ${result.name} (${result.count}/${MAX_PHOTOS}), ${result.dupes} already in it`);
            } else {
                toast(`Added to ${result.name} (${result.count}/${MAX_PHOTOS})`);
            }
            if (onDone) onDone();
        });
    }

    /** Bottom sheet listing posts. Default: adds refs to the chosen post.
     *  With opts.selectOnly it just switches the current post (no adding). */
    function openPicker(refs, onDone, opts) {
        const selectOnly = !!(opts && opts.selectOnly);
        ready.then(ok => {
            if (!ok) { toast('Posts unavailable, try re-entering the password at /posts'); return; }
            const overlay = document.createElement('div');
            overlay.className = 'posts-picker-overlay';
            const sheet = document.createElement('div');
            sheet.className = 'posts-picker';
            const title = document.createElement('h3');
            title.textContent = selectOnly ? 'Set current post'
                : refs.length === 1 ? 'Add photo to' : `Add ${refs.length} photos to`;
            sheet.appendChild(title);

            const close = () => overlay.remove();
            const choose = postId => {
                close();
                if (!selectOnly) { addToPost(postId, refs, onDone); return; }
                const existing = doc.posts.find(p => p.id === postId);
                if (existing) {
                    setTarget(postId);
                    updateSelectUi();
                    restampSelections();
                    toast(`Current post: ${existing.name}`);
                    if (onDone) onDone();
                    return;
                }
                const result = {};
                mutate(posts => {
                    if (!posts.find(p => p.id === postId)) {
                        const post = { id: postId, name: defaultName(posts), created: new Date().toISOString(), photos: [] };
                        posts.push(post);
                        result.name = post.name;
                    }
                }).then(okSave => {
                    if (!okSave) return;
                    setTarget(postId);
                    updateSelectUi();
                    restampSelections();
                    toast(`Current post: ${result.name}`);
                    if (onDone) onDone();
                });
            };

            const current = targetPost();
            doc.posts.forEach(p => {
                const row = document.createElement('button');
                row.type = 'button';
                row.className = 'posts-picker-row';
                if (p.photos.length >= MAX_PHOTOS) row.classList.add('posts-picker-full');
                if (current && current.id === p.id) row.classList.add('posts-picker-current');
                row.innerHTML = `<span class="posts-picker-name"></span><span class="posts-picker-count"></span>`;
                row.querySelector('.posts-picker-name').textContent = p.name;
                row.querySelector('.posts-picker-count').textContent = (current && current.id === p.id ? 'current · ' : '')
                    + `${p.photos.length}/${MAX_PHOTOS}`;
                row.addEventListener('click', () => choose(p.id));
                sheet.appendChild(row);
            });

            const create = document.createElement('button');
            create.type = 'button';
            create.className = 'posts-picker-row posts-picker-new';
            create.textContent = '+ New post';
            create.addEventListener('click', () => choose(newId()));
            sheet.appendChild(create);

            const cancel = document.createElement('button');
            cancel.type = 'button';
            cancel.className = 'posts-picker-cancel';
            cancel.textContent = 'Cancel';
            cancel.addEventListener('click', close);
            sheet.appendChild(cancel);

            overlay.addEventListener('click', e => { if (e.target === overlay) close(); });
            overlay.appendChild(sheet);
            document.body.appendChild(overlay);
        });
    }

    // ---------- Lightbox button ----------

    let currentGallery = null;

    function attachLightbox(gallery, pswpEl) {
        currentGallery = gallery;
        gallery.listen('destroy', () => { if (currentGallery === gallery) currentGallery = null; });
        const bar = pswpEl && pswpEl.querySelector('.pswp__top-bar');
        if (!bar || bar.querySelector('.posts-add-btn')) return;
        const btn = document.createElement('button');
        btn.type = 'button';
        btn.className = 'pswp__button posts-add-btn';
        btn.title = 'Add to post';
        btn.textContent = '+ Post';
        btn.addEventListener('click', e => {
            e.stopPropagation();
            const item = currentGallery && currentGallery.currItem;
            if (!item || !item.ref) { toast('This photo cannot be added'); return; }
            ready.then(ok => {
                if (!ok) { toast('Posts unavailable, try re-entering the password at /posts'); return; }
                const t = targetPost();
                if (t) addToPost(t.id, [item.ref]);   // straight into the current post
                else openPicker([item.ref]);          // no current post yet: ask once
            });
        });
        const pick = document.createElement('button');
        pick.type = 'button';
        pick.className = 'pswp__button posts-pick-btn';
        pick.title = 'Choose which post "+ Post" adds to';
        pick.textContent = '▾';
        pick.addEventListener('click', e => {
            e.stopPropagation();
            openPicker([], null, { selectOnly: true });
        });
        const closeBtn = bar.querySelector('.pswp__button--close');
        bar.insertBefore(btn, closeBtn || null);
        bar.insertBefore(pick, closeBtn || null);
    }

    // ---------- Grid select mode ----------

    let selectMode = false;
    const selected = new Map();   // key -> ref
    const refByKey = new Map();   // key -> ref, for every grid photo seen on this page
    let fab = null, actionBar = null, actionCount = null, actionTarget = null, actionAdd = null;

    function ensureSelectUi() {
        if (fab) return;
        fab = document.createElement('button');
        fab.type = 'button';
        fab.id = 'posts-fab';
        fab.textContent = 'Select';
        fab.title = 'Select photos for a post';
        fab.addEventListener('click', () => setSelectMode(!selectMode));
        document.body.appendChild(fab);

        actionBar = document.createElement('div');
        actionBar.id = 'posts-actionbar';
        actionCount = document.createElement('span');
        actionCount.className = 'posts-action-count';
        actionTarget = document.createElement('button');
        actionTarget.type = 'button';
        actionTarget.className = 'posts-action-target';
        actionTarget.title = 'Change which post photos are added to';
        actionTarget.addEventListener('click', () => openPicker([], null, { selectOnly: true }));
        actionAdd = document.createElement('button');
        actionAdd.type = 'button';
        actionAdd.className = 'posts-action-add';
        actionAdd.textContent = 'Add';
        actionAdd.addEventListener('click', () => {
            if (!selected.size) { toast('Nothing selected'); return; }
            const refs = [...selected.values()];
            const t = targetPost();
            if (t) addToPost(t.id, refs, () => setSelectMode(false));  // straight into the current post
            else openPicker(refs, () => setSelectMode(false));         // no current post yet: ask once
        });
        const cancel = document.createElement('button');
        cancel.type = 'button';
        cancel.className = 'posts-action-cancel';
        cancel.textContent = 'Cancel';
        cancel.addEventListener('click', () => setSelectMode(false));
        actionBar.append(actionCount, actionTarget, actionAdd, cancel);
        document.body.appendChild(actionBar);
    }

    function setSelectMode(on) {
        selectMode = on;
        if (!on) selected.clear();
        document.body.classList.toggle('posts-selecting', on);
        updateSelectUi();
        restampSelections();
    }

    function updateSelectUi() {
        if (!fab) return;
        fab.classList.toggle('active', selectMode);
        fab.textContent = selectMode ? 'Selecting...' : 'Select';
        actionBar.classList.toggle('visible', selectMode);
        actionCount.textContent = selected.size > MAX_PHOTOS
            ? `${selected.size} selected (max ${MAX_PHOTOS} per post)`
            : `${selected.size} selected`;
        const t = targetPost();
        actionTarget.textContent = t ? `${t.name} · ${t.photos.length}/${MAX_PHOTOS}` : 'Choose post';
        actionAdd.textContent = t ? 'Add' : 'Add to post';
    }

    function restampSelections() {
        const t = selectMode ? targetPost() : null;
        const inTarget = t ? new Set(t.photos.map(keyOf)) : null;
        document.querySelectorAll('.photo-cell[data-trip]').forEach(cell => {
            const key = `${cell.dataset.trip}::${cell.dataset.id}`;
            cell.classList.toggle('posts-selected', selectMode && selected.has(key));
            cell.classList.toggle('posts-in-target', !!inTarget && inTarget.has(key));
        });
    }

    // Capture phase: runs before the cell's own click handler, so in select
    // mode a tap toggles selection instead of opening the lightbox.
    document.addEventListener('click', e => {
        if (!selectMode) return;
        const cell = e.target.closest && e.target.closest('.photo-cell');
        if (!cell || !cell.dataset.trip) return;
        e.preventDefault();
        e.stopImmediatePropagation();
        const key = `${cell.dataset.trip}::${cell.dataset.id}`;
        if (selected.has(key)) {
            selected.delete(key);
        } else {
            const t = targetPost();
            if (t && t.photos.some(ph => keyOf(ph) === key)) {
                toast(`Already in ${t.name}`);
                return;
            }
            const ref = refByKey.get(key) || { trip: cell.dataset.trip, id: cell.dataset.id };
            selected.set(key, ref);
        }
        cell.classList.toggle('posts-selected', selected.has(key));
        updateSelectUi();
    }, true);

    /** Called by gallery.js after every grid (re)layout. */
    function onGridRender(grid, order) {
        (order || []).forEach(ref => {
            if (ref && ref.trip && ref.id) refByKey.set(keyOf(ref), ref);
        });
        ready.then(ok => { if (ok) ensureSelectUi(); });
        restampSelections();   // relayout rebuilds cells, so re-apply check marks
    }

    // ---------- /posts manager page ----------

    function initPostsPage() {
        const root = document.getElementById('posts-app');
        if (!root) return;
        Promise.all([ready, autoReady()]).then(([ok]) => {
            if (!ok) {
                // Cookie present but the API rejects it (stale after a password
                // change): fall back to the prompt instead of a dead page.
                renderPasswordForm(root);
                return;
            }
            renderManager(root);
        });
    }

    // Which manager tab is showing: 'main' (hand-made drafts) or 'auto'
    // (suggestions generated by tools/auto_curate_posts.py).
    let activeTab = 'main';
    try { activeTab = localStorage.getItem('posts_tab') || 'main'; } catch (e) { /* private mode */ }

    function renderManager(root) {
        root.innerHTML = '';
        const head = document.createElement('div');
        head.className = 'posts-head';
        const h1 = document.createElement('h1');
        h1.textContent = 'Posts';
        head.appendChild(h1);
        if (activeTab === 'main') {
            const newBtn = document.createElement('button');
            newBtn.type = 'button';
            newBtn.className = 'posts-new-btn';
            newBtn.textContent = '+ New post';
            newBtn.addEventListener('click', () => {
                mutate(posts => {
                    posts.push({ id: newId(), name: defaultName(posts), created: new Date().toISOString(), photos: [] });
                }).then(() => renderManager(root));
            });
            head.appendChild(newBtn);
        }
        root.appendChild(head);

        const tabs = document.createElement('div');
        tabs.className = 'posts-tabs';
        const autoCount = autoDoc ? autoDoc.posts.length : 0;
        [['main', `My posts (${doc.posts.length})`],
         ['auto', `Auto curated (${autoCount})`]].forEach(([id, label]) => {
            const b = document.createElement('button');
            b.type = 'button';
            b.className = 'posts-tab' + (activeTab === id ? ' active' : '');
            b.textContent = label;
            b.addEventListener('click', () => {
                activeTab = id;
                try { localStorage.setItem('posts_tab', id); } catch (e) { /* private mode */ }
                renderManager(root);
            });
            tabs.appendChild(b);
        });
        root.appendChild(tabs);

        if (activeTab === 'auto') {
            renderAutoList(root);
            return;
        }

        if (!doc.posts.length) {
            const empty = document.createElement('p');
            empty.className = 'posts-empty';
            empty.textContent = 'No post drafts yet. Browse anywhere on the site and use "+ Post" in the photo viewer, or "Select" on any photo grid.';
            root.appendChild(empty);
            return;
        }

        doc.posts.forEach(post => root.appendChild(renderCard(root, post, 'main')));
    }

    const THEME_LABELS = {
        custom: 'Custom curated', story: 'Behind the scenes', province: 'By province',
        place: 'Places', industrial: 'Industry', nature: 'Nature', wildlife: 'Wildlife'
    };

    // Local-only curation server (tools/curate_server.py): free-text queries
    // become curated posts. Probed once; the box only appears when it runs.
    let curateBaseP = null;
    function curateBase() {
        if (!curateBaseP) {
            const base = `http://${location.hostname}:8799`;
            let signal;
            try { signal = AbortSignal.timeout(1500); } catch (e) { signal = undefined; }
            curateBaseP = fetch(base + '/health', { signal })
                .then(r => (r.ok ? base : null))
                .catch(() => null);
        }
        return curateBaseP;
    }

    function renderCurateBar(root, container) {
        curateBase().then(base => {
            if (!base) return;
            const bar = document.createElement('div');
            bar.className = 'posts-curate-bar';
            const input = document.createElement('input');
            input.type = 'text';
            input.className = 'posts-curate-input';
            input.placeholder = 'Curate by prompt, e.g. "truck stops in china" or "central asia landscapes"';
            const btn = document.createElement('button');
            btn.type = 'button';
            btn.className = 'posts-copy-btn';
            btn.textContent = 'Curate';
            async function run() {
                const q = input.value.trim();
                if (!q) return;
                btn.disabled = true;
                btn.textContent = 'Curating...';
                try {
                    const r = await fetch(base + '/curate?q=' + encodeURIComponent(q));
                    const data = await r.json();
                    if (!r.ok) throw new Error(data.error || ('HTTP ' + r.status));
                    if (!data.posts.length) {
                        toast(`No good matches for "${q}"`);
                        return;
                    }
                    await mutateSet('auto', posts => {
                        const ids = new Set(data.posts.map(p => p.id));
                        for (let i = posts.length - 1; i >= 0; i--) {
                            if (ids.has(posts[i].id)) posts.splice(i, 1);
                        }
                        posts.unshift(...data.posts);
                    });
                    toast(`Curated ${data.posts.length} post${data.posts.length > 1 ? 's' : ''} for "${q}"`);
                    renderManager(root);
                } catch (e) {
                    toast('Curate failed: ' + e.message);
                } finally {
                    btn.disabled = false;
                    btn.textContent = 'Curate';
                }
            }
            input.addEventListener('keydown', e => { if (e.key === 'Enter') run(); });
            btn.addEventListener('click', run);
            bar.append(input, btn);
            container.appendChild(bar);
        });
    }

    function renderAutoList(root) {
        const curateSlot = document.createElement('div');
        root.appendChild(curateSlot);
        renderCurateBar(root, curateSlot);
        if (!autoDoc) {
            const p = document.createElement('p');
            p.className = 'posts-empty';
            p.textContent = 'Auto-curated posts are unavailable (API error).';
            root.appendChild(p);
            return;
        }
        if (!autoDoc.posts.length) {
            const p = document.createElement('p');
            p.className = 'posts-empty';
            p.textContent = 'No auto-curated suggestions yet. Run tools/auto_curate_posts.py --push to generate them.';
            root.appendChild(p);
            return;
        }
        let lastTheme = null;
        autoDoc.posts.forEach(post => {
            const theme = post.theme || 'other';
            if (theme !== lastTheme) {
                lastTheme = theme;
                const h = document.createElement('h2');
                h.className = 'posts-theme-head';
                h.textContent = THEME_LABELS[theme] || theme;
                root.appendChild(h);
            }
            root.appendChild(renderCard(root, post, 'auto'));
        });
    }

    function renderCard(root, post, set) {
        set = set || 'main';
        const M = fn => mutateSet(set, fn);
        const card = document.createElement('section');
        card.className = 'posts-card';

        const bar = document.createElement('div');
        bar.className = 'posts-card-bar';
        const name = document.createElement('input');
        name.className = 'posts-name';
        name.value = post.name;
        name.addEventListener('change', () => {
            const v = name.value.trim() || post.name;
            name.value = v;
            M(posts => {
                const p = posts.find(x => x.id === post.id);
                if (p) p.name = v;
            });
        });
        const count = document.createElement('span');
        count.className = 'posts-count';
        count.textContent = `${post.photos.length}/${MAX_PHOTOS} photos`;
        if (post.photos.length >= MAX_PHOTOS) count.classList.add('posts-count-full');
        const del = document.createElement('button');
        del.type = 'button';
        del.className = 'posts-delete';
        del.textContent = set === 'auto' ? 'Dismiss' : 'Delete';
        del.addEventListener('click', () => {
            const verb = set === 'auto' ? 'Dismiss' : 'Delete';
            if (!confirm(`${verb} "${post.name}"? The photos themselves are not affected.`)) return;
            M(posts => {
                const i = posts.findIndex(x => x.id === post.id);
                if (i !== -1) posts.splice(i, 1);
            }).then(() => renderManager(root));
        });
        bar.append(name, count);
        if (set === 'auto') {
            // Promote a suggestion into the hand-made drafts (which is what
            // posts_pull.py pulls); the suggestion itself stays until dismissed.
            const copy = document.createElement('button');
            copy.type = 'button';
            copy.className = 'posts-copy-btn';
            copy.textContent = 'Copy to My posts';
            copy.addEventListener('click', () => {
                const dup = {
                    id: newId(), name: post.name, created: new Date().toISOString(),
                    photos: post.photos.map(cleanRef)
                };
                if (post.phone && post.phone.length) dup.phone = post.phone.map(cleanPhoneRef);
                mutate(posts => {
                    if (!posts.some(p => p.name === dup.name)) posts.push(dup);
                }).then(okSave => {
                    if (okSave) toast(`Copied "${post.name}" to My posts`);
                    renderManager(root);
                });
            });
            bar.appendChild(copy);
        }
        bar.appendChild(del);
        // Local-only phone-library companion: shows phone photos taken around
        // the same time as this post's camera picks. No-op when the phone
        // library (or the script) is absent.
        if (window.PhoneCompanion) PhoneCompanion.decorateCard(bar, post);
        card.appendChild(bar);
        if (set === 'auto' && post.note) {
            const note = document.createElement('p');
            note.className = 'posts-note';
            note.textContent = post.note;
            card.appendChild(note);
        }

        const strip = document.createElement('div');
        strip.className = 'posts-strip';
        post.photos.forEach((ref, idx) => strip.appendChild(renderThumb(root, post, ref, idx, set)));
        if (!post.photos.length) {
            const hint = document.createElement('p');
            hint.className = 'posts-empty';
            hint.textContent = 'Empty. Add photos from anywhere on the site.';
            strip.appendChild(hint);
        }
        card.appendChild(strip);

        // Collapsible behind-the-scenes bucket from the local phone library
        // (uncapped, pulled into a Phone/ subfolder by posts_pull.py).
        if (post.phone && post.phone.length) {
            const det = document.createElement('details');
            det.style.cssText = 'margin-top:8px';
            const sum = document.createElement('summary');
            sum.textContent = `Phone (${post.phone.length})`;
            sum.style.cssText = 'cursor:pointer;opacity:.75;font-size:13px';
            const pstrip = document.createElement('div');
            pstrip.className = 'posts-strip';
            const photoRefs = post.phone.filter(r => r.id);
            post.phone.forEach(ref => {
                const cell = document.createElement('div');
                cell.style.cssText = 'position:relative;flex:0 0 auto';
                if (ref.id) {
                    const img = document.createElement('img');
                    img.src = window.Gallery ? Gallery.photoUrl(ref, 'thumbnails') : '';
                    img.loading = 'lazy';
                    img.style.cssText = 'height:96px;border-radius:5px;display:block;cursor:pointer';
                    img.addEventListener('click', () => {
                        if (window.Gallery) Gallery.openLightbox(photoRefs, photoRefs.indexOf(ref));
                    });
                    cell.appendChild(img);
                } else {
                    const vid = document.createElement('a');
                    vid.href = `/phone/trips/${ref.trip}/videos/` +
                        ref.file.split('/').map(encodeURIComponent).join('/');
                    vid.target = '_blank';
                    vid.style.cssText = 'height:96px;width:128px;border-radius:5px;background:#26262c;' +
                        'color:#ddd;display:flex;flex-direction:column;align-items:center;' +
                        'justify-content:center;gap:3px;text-decoration:none';
                    const play = document.createElement('span');
                    play.textContent = '▶';
                    play.style.cssText = 'font-size:22px';
                    const lbl = document.createElement('span');
                    lbl.textContent = ref.file.split('/').pop().slice(0, 16);
                    lbl.style.cssText = 'font-size:9px;opacity:.7';
                    vid.append(play, lbl);
                    cell.appendChild(vid);
                }
                const rm = document.createElement('button');
                rm.type = 'button';
                rm.textContent = '✕';
                rm.title = 'Remove from Phone section';
                rm.style.cssText = 'position:absolute;top:3px;right:3px;background:rgba(0,0,0,.65);' +
                    'color:#fff;border:none;border-radius:4px;cursor:pointer;font-size:11px;padding:1px 5px';
                rm.addEventListener('click', () => {
                    M(posts => {
                        const pp = posts.find(x => x.id === post.id);
                        if (!pp || !pp.phone) return;
                        const i = pp.phone.findIndex(r => keyOf(r) === keyOf(ref));
                        if (i !== -1) pp.phone.splice(i, 1);
                        if (!pp.phone.length) delete pp.phone;
                    }).then(() => renderManager(root));
                });
                cell.appendChild(rm);
                pstrip.appendChild(cell);
            });
            det.append(sum, pstrip);
            card.appendChild(det);
        }
        return card;
    }

    function renderThumb(root, post, ref, idx, set) {
        const M = fn => mutateSet(set || 'main', fn);
        const cell = document.createElement('div');
        cell.className = 'posts-thumb';
        cell.draggable = true;

        const orderBadge = document.createElement('span');
        orderBadge.className = 'posts-order';
        orderBadge.textContent = idx + 1;

        const img = document.createElement('img');
        img.loading = 'lazy';
        img.decoding = 'async';
        img.alt = '';
        img.src = window.Gallery ? Gallery.photoUrl(ref, 'thumbnails') : '';
        img.addEventListener('error', () => { if (window.Gallery) Gallery.lockedCover(img); });
        img.addEventListener('click', () => {
            if (window.Gallery) Gallery.openLightbox(post.photos, idx);
        });

        const move = pos => M(posts => {
            const p = posts.find(x => x.id === post.id);
            if (!p) return;
            const from = p.photos.findIndex(ph => keyOf(ph) === keyOf(ref));
            if (from === -1) return;
            const to = Math.max(0, Math.min(p.photos.length - 1, pos));
            p.photos.splice(to, 0, p.photos.splice(from, 1)[0]);
        }).then(() => renderManager(root));

        const controls = document.createElement('div');
        controls.className = 'posts-thumb-controls';
        const left = document.createElement('button');
        left.type = 'button'; left.textContent = '◀'; left.title = 'Move earlier';
        left.disabled = idx === 0;
        left.addEventListener('click', () => move(idx - 1));
        const right = document.createElement('button');
        right.type = 'button'; right.textContent = '▶'; right.title = 'Move later';
        right.disabled = idx === post.photos.length - 1;
        right.addEventListener('click', () => move(idx + 1));
        // Face-blur mark: flags this photo so posts_pull.py copies a
        // face-pixelated version instead of the straight original.
        const blurBtn = document.createElement('button');
        blurBtn.type = 'button';
        blurBtn.textContent = '🙂';
        blurBtn.title = ref.blur ? 'Face blur ON — pull copies a censored version'
                                 : 'Blur faces when pulled';
        if (ref.blur) blurBtn.style.cssText = 'background:#1d4ed8;border-radius:4px';
        blurBtn.addEventListener('click', () => {
            M(posts => {
                const p = posts.find(x => x.id === post.id);
                if (!p) return;
                const ph = p.photos.find(x => keyOf(x) === keyOf(ref));
                if (!ph) return;
                if (ph.blur) delete ph.blur; else ph.blur = true;
            }).then(() => renderManager(root));
        });

        const rm = document.createElement('button');
        rm.type = 'button'; rm.textContent = '✕'; rm.title = 'Remove from post';
        rm.addEventListener('click', () => {
            M(posts => {
                const p = posts.find(x => x.id === post.id);
                if (!p) return;
                const i = p.photos.findIndex(ph => keyOf(ph) === keyOf(ref));
                if (i !== -1) p.photos.splice(i, 1);
            }).then(() => renderManager(root));
        });
        controls.append(left, rm, right);

        // Desktop drag to reorder; phones use the arrow buttons.
        cell.addEventListener('dragstart', e => {
            e.dataTransfer.setData('text/plain', keyOf(ref));
            e.dataTransfer.effectAllowed = 'move';
        });
        cell.addEventListener('dragover', e => { e.preventDefault(); cell.classList.add('drag-over'); });
        cell.addEventListener('dragleave', () => cell.classList.remove('drag-over'));
        cell.addEventListener('drop', e => {
            e.preventDefault();
            cell.classList.remove('drag-over');
            const fromKey = e.dataTransfer.getData('text/plain');
            if (!fromKey || fromKey === keyOf(ref)) return;
            M(posts => {
                const p = posts.find(x => x.id === post.id);
                if (!p) return;
                const from = p.photos.findIndex(ph => keyOf(ph) === fromKey);
                const to = p.photos.findIndex(ph => keyOf(ph) === keyOf(ref));
                if (from === -1 || to === -1) return;
                p.photos.splice(to, 0, p.photos.splice(from, 1)[0]);
            }).then(() => renderManager(root));
        });

        controls.insertBefore(blurBtn, rm);
        if (ref.blur) {
            const mark = document.createElement('span');
            mark.textContent = '🙂🚫';
            mark.title = 'Faces will be blurred on pull';
            mark.style.cssText = 'position:absolute;bottom:4px;left:4px;font-size:12px;' +
                'background:rgba(0,0,0,.65);border-radius:4px;padding:1px 4px';
            cell.appendChild(mark);
        }
        cell.append(orderBadge, img, controls);
        return cell;
    }

    // Blogs render their grids synchronously from inline JSON before this
    // script loads, so their onGridRender call never happens — pick up any
    // already-rendered grid once the state is in.
    ready.then(ok => {
        if (ok && document.querySelector('.photo-cell[data-trip]')) ensureSelectUi();
    });

    return { enabled: true, attachLightbox, onGridRender, initPostsPage, addToPost };
})();
